# Generated by Django 4.2.16 on 2024-09-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_flag_delete_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='image',
            field=models.ImageField(upload_to='app/static/images/flags/'),
        ),
    ]
